server:
  port: 8277

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

spring:
  application:
    name: orders
  main:
    allow-circular-references: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#feign:
#  httpclient:
#    enabled=true:

