server:
  port: 8111



eureka:
  client:
#   registerWithEureka: true
    serviceUrl:
      defaulZone: http://localhost:8761/eureka



spring:
  application:
   name: gateway
  cloud:
   gateway:
    routes:
      - id: notifications
        uri: lb://notifications
        predicates:
                  - Path=/notifications/**
      - id: users
        uri: lb://users
        predicates:
                  - Path=/users/**
      - id: orders
        uri: lb://orders
        predicates:
                  - Path=/orders/**
      - id: products
        uri: lb://products
        predicates:
                 - Path=/products/**
#zuul:
#  routes:
#     users:
#       path: /users/**
#     orders:
#       path: /orders/**
#     products:
#       path: /products/**
#     notifications:
#       path: localhost:8984/notifications/**
#     c:
#       path: /cat/**


#
#spring:
#  application:
#    name: gateway2
#  cloud:
#    gateway:
#      routes:
#        - id: studentModule
#          uri: lb://student-service
#          predicates:
#            - Path=/student/**
#        - id: courseModule
#          uri: lb://course-service
#          predicates:
#            - Path=/course/**


ribbon:
  ReadTimeout: 10000

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG



#server:
#  port: 8111
#
#spring:
#  application:
#    name: gateway
#  cloud:
#    gateway:
#      routes:
#        - id: studentModule
#          uri: lb://student-service
#          predicates:
#            - Path=/student/**
#        - id: courseModule
#          uri: lb://course-service
#          predicates:
#            - Path=/course/**

#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka